### ISSUE TITLE
Save-Button

### ISSUE THREAD

**Issue by wtczk** [ControlExpert/chrome-multiwindow-positioner#12]
Let me say first of all: awesome extension!

But what I don't get is why after clicking on the 'save button' the tab will be closed?
It would be better to add a 'close button' and remove that function from the 'save button'.

**Comment by igorlino** [comment]
There new version 1.0. has updated  the bar design. Its is theoretically easier to add the close button now.
So far other users have been happy.

But from other perspective, a real use case is that, you may want to test your changes, so it would be a time-consuming saving changes.

**alternative idea:**
Maybe add it as 'apply' button
and rename save -> save&close

**Comment by igorlino** [comment]
Temporally adding as save & apply.
We are missing icons for a proper distinction between both use cases.

**Comment by igorlino** [comment]
Tab is not closed anymore. :)

**Comment by StevenJokes** [comment]
Are there some ways to save the json to my computer?Then, I can upload it to another browser..

**Comment by StevenJokes** [comment]
save my tab rules to json..
