### ISSUE TITLE
Usage Instructions

### ISSUE THREAD

**Issue by afiorillo** [ControlExpert/chrome-multiwindow-positioner#21]
Hi!

This extension looks like exactly what I've been searching for, and the configuration seems very straightforward. It's not entirely clear what the extension does outside of setting a configuration though. Am I missing something?

I would be more than happy to write up usage instructions (like mentioned in #1 ) if I can figure out how to use the extension myself.

## Example:
I have three monitors (with my main Chrome window on Monitor 3).
I've configured MultiWindow Positioner with the YouTube template and selected Monitor 1 as the monitor.
After trying opening a new tab and navigating to YouTube, opening a new window and navigating to YouTube, opening a link to YouTube in a new tab, and opening a link to YouTube in a new window there is no obvious change made by the extension.

Thanks!

**Comment by ceilino** [comment]
Hi, sorry, was too busy. Some good news: I have added a help getting started section.

See line 509 of [options.html](https://github.com/ControlExpert/chrome-multiwindow-positioner/blob/master/app/options.html)

If you would like to add more clear parts, you are most welcome to contribute.

For the issue of yours: can be that that the template rule is insufficient, please try with the full URL, then slow remove parts of it, and see that it keeps working.
BTW: the rules only apply when there are pop windows, other types of tabs when you enter the URL are ignored by rules.
