### ISSUE TITLE
Needs x,y co-ords & width,height options - current options are not helpful

### ISSUE THREAD

**Issue by TheNicholasNick** [ControlExpert/chrome-multiwindow-positioner#22]
I have YouTube in a plain window already via the whole add to desktop deal.
What I need now is a way to keep the window at 2559,-1 that is 1282 wide, 752 high.

Cheers

**Comment by igorlino** [comment]
Yes, correct, there are no custom position setting, only predefined window positions.

**Comment by TheNicholasNick** [comment]
seems fairly simple to adjust, having a look into it

**Comment by driedger** [comment]
I cloned this project and hacked in some custom positions which I needed for similar reasons as mentioned above. An interface to add more custom positions/sizes would be a fantastic addition to this project!

**Comment by igorlino** [comment]
next version, v1.0.12 or v.1.0.13 (publish is in progress) contains: 
- custom positions can be set. 
- maximized mode fixed

1) Click the 'show more options' which will show an additional table where you  can click the + button and get to define a custom position.

2) The custom position can then be selected by the rule.

3) Save

**Comment by igorlino** [comment]
@driedger If you be so kind, you could improve the documentation. I will be happy to accept PR for nicer user documentation.
